# Generated by Django 5.1.3 on 2026-04-24 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_servicedb'),
        ('WebApp', '0005_checkoutdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='productViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='AdminApp.productdb')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
